### ISSUE TITLE
Error while starting UI service

### ISSUE THREAD

**Issue by arpit2010** [airavata-courses/Yoda#116]
While starting UI service by running npm start, it fails with the error as shown in the screenshot.
![yoda_ui_bug](https://user-images.githubusercontent.com/8495322/75317791-d7c96600-5836-11ea-8dc0-68ec159223ed.JPG)

**Comment by gouthamgopal** [comment]
Hi @arpit2010,

The error was due to an issue with the naming convention within the folder structure. The modifications have been committed to the release branch. 

Apart from that, if you trying to run in linux, you might run into a no space error, while running npm start, as ENOSPC.

If you encounter such error then run the below command in the terminal:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Run `npm install` and then run `npm start`.

You should be landing on the homepage of our application.
